# Generated by Django 2.2 on 2019-04-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='released_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
