# Generated by Django 2.2 on 2019-04-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20190411_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
